config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:new, :create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth", as: "facebook_login"

  resources :listings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :tags, :through => :taggings
  has_many :taggings

  validates :title, presence: true
  validates :address, presence: true
  validates :pax, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :listings, :through => :taggings
  has_many :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :listing
  belongs_to :tag
end

app/models/user.rb
require 'carrierwave/orm/activerecord'

class User < ApplicationRecord
  include Clearance::User 

  mount_uploader :avatar, AvatarUploader
  
  validates_confirmation_of :password

  validates :first_name,            presence: true
  validates :last_name,             presence: true
  has_many  :authentications,       dependent: :destroy
  has_many  :listings,              dependent: :destroy



  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(
                          first_name: get_first_name(auth_hash[:info][:name]),
                          last_name:  get_last_name(auth_hash[:info][:name]),
                          email:      auth_hash[:info][:email]
                          )
      user.authentications << (authentication)      
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    byebug
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
  
  def self.get_first_name(full_name)
    full_name.split(" ")[0]
  end

  def self.get_last_name(full_name)
    full_name.split(" ")[1..-1].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_login
  
  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
  end
  
  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Successfully listed!" }
      else
        format.html { redirect_to new_listing_path, notice: "Failed" }
        format.js
      end
    end    
  end

  def edit
    @listing = Listing.find(params[:id])  
  end

  def update
    @listing = Listing.find(params[:id])
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing updated!" }
      else
        format.html { redirect_to edit_listing_path, notice: "Failed to update" }
        format.js
      end
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:success] = "Deleted listing"
    redirect_to root_path
  end

  private
  def listing_params
    params.require(:listing).permit(:title,:address,:pax,:user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication, auth_hash)
      @next = edit_user_path(user)
      @notice = "User created - confirm or edit details..."
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

def new
	@user = User.new
end

def create
	@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Success!"
			redirect_to @user
		else
			flash[:error] = "Failed.."
			redirect_to :back
		end
end

def show
	@user = User.find(params[:id])
	@listings = @user.listings.paginate(page: params[:page])
end

def edit
	@user = User.find(params[:id])
end

def update
	@user = User.find(params[:id])
	byebug
	@user.update(user_params)
	redirect_to @user
end

private
	def user_params
		params.require(:user).permit(:first_name,:last_name,:email,:password, :password_confirmation, :avatar)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		#anything to display on root? put here.
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/listings_helper.rb
module ListingsHelper

def owner?
  if current_user.id == @listing.user_id
    true
  else
    false
  end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_path %>
  <br>
	<% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <%= link_to "Profile", current_user %>
      <%= link_to "Create   Listing", new_listing_path %>
      <%= image_tag(current_user.avatar_url(:thumb).to_s, id: "avatar") %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path, id: "sign_in", remote: true %>
      <%= link_to 'Sign up', sign_up_path, id: "sign_up" %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>

  </body>
</html>

app/views/listings/_form.html.erb
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :address %>
  <%= form.text_field :address %><br>

  <%= form.label :pax %>
  <%= form.text_field :pax %><br>

  <%= form.submit %>

app/views/listings/create.js.erb
$(".errors").remove()
<% @listing.errors.messages.map do |key, value| %>
  $("#listing_<%= key %>").after("   <span class='errors' style='color:red;'><%= key %> <%= value[0] %></span>")
<% end %>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>
<%= form_for @listing, remote: true do |form| %>
    <%= render partial: '/listings/form', object: form %>
<% end %>

app/views/listings/index.html.erb
<h1>Listings#index</h1>
<p>Find me in app/views/listings/index.html.erb</p>

app/views/listings/new.html.erb
<h1>Listings#new</h1>
<%= form_for @listing, remote: true do |form| %>
    <%= render partial: '/listings/form', object: form %>
<% end %>

app/views/listings/show.html.erb
<h1>Listings#show</h1>
<p>Find me in app/views/listings/show.html.erb</p>
<% if owner? %>
  <%= link_to "Edit", edit_listing_path(@listing) %>
<% end %>
<ul>
  <li><%=@listing.title%></li>
  <li><%=@listing.address%></li>
  <li><%=@listing.pax%></li>
</ul>

app/views/listings/update.js.erb
<% @listing.errors.messages.map do |key, value| %>
  $("#listing_<%= key %>").after("   <span style='color:red;'><%= key %> <%= value[0] %></span>")
<% end %>

app/views/users/_form.html.erb
    <div class="text-field" id="first_name">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, type: 'text' %>
    </div>

    <div class="text-field" id="last_name">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, type: 'text' %>
    </div>

    <div class="text-field" id="email">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email' %>
    </div>

    <div class="password-field" id="password">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="password-field" id="password_confirmation">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation	 %>
    </div>

    <%= form.label :avatar %>
    <%= form.file_field :avatar %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

app/views/users/create.js.erb
// $(".sign_up_errors").remove();
// <% @user.errors.full_messages.each do |error| %>
// 	$("h2").after("<li class='sign_up_errors' style='color:red;'><%= error %></li>")
// <% end %>

console.log("<%= @user.errors.messages %>")

$(".errors").remove()
<% @user.errors.messages.map do |key, value| %>
  $("#user_<%= key %>").after("   <span class='errors'style='color:red;'><%= key %> <%= value[0] %></span>")
<% end %>

app/views/users/edit.erb
<div>
  <h2>Edit</h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
  <% end %>
  
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

<%= form_for @user do |form| %>
  <%= render partial: '/users/form', object: form %>
<% end %>

</div>

app/views/users/show.erb
<h3>Details</h3>
<ul>
  <li><%= @user.first_name %></li>
  <li><%= @user.last_name %></li>
  <li><%= @user.email %></li>
</ul>

<h3>Listings</h3>
<ul>
  <% @listings.each_with_index do |listing,i| %>
    <li>Title: <%= link_to "[#{i}] #{listing.title}", listing %>, Pax: <%= listing.pax%></li>
  <% end %>
</ul>

<%= will_paginate @listings %>

app/views/welcome/index.erb
<h1> Welcome to Index </h1>